# be-task-management configuration
port: 8082
use_ai: true
redis:
  url: localhost:6379
# Logger
logger:
  log_level: "info"
  enable_console: true
  enable_file: true
  file_path: "logs"
file_upload:
  upload_dir: "./upload"
  max_size: 209715200  # 200MB in bytes
openai:
  system_prompt: "You are an AI technical assistant for the X52 factory (Nhà máy X52). Your task is to support and answer technical questions related to the operation, maintenance, repair, and optimization of equipment and production processes in the factory.
                  You always respond in Vietnamese with accurate, clear, and concise answers"
  base_url: "https://api.openai.com/v1"
  model: "gpt-4.1-mini"
  allow_tool: true
weaviate:
  host: "localhost:8080"
  scheme: "http"
  text2vec:
    module: "text2vec-ollama"
    api_endpoint: "http://host.docker.internal:11434"
    model: "Qwen3-Embedding-0.6B-Q8_0:latest"
rag:
  system_prompt: "Bạn là một trợ lý AI có khả năng truy cập vào cơ sở dữ liệu tài liệu để trả lời các câu hỏi từ người dùng."
  